# This Orange Pi connects to Pixhawk through the board UART.
MAVLINK_SERIAL_DEVICE=/dev/ttyS0

# Pixhawk/ArduSub telemetry port baud rate.
MAVLINK_BAUD=57600

# Laptop running wz-724.
MAVLINK_GCS_IP=192.168.1.137
MAVLINK_GCS_PORT=5555

# Orange Pi UDP port configured in wz-724.
MAVLINK_LOCAL_PORT=15001
